### ISSUE TITLE
Songs and albums are editable by any artist

### ISSUE THREAD

**Issue by Hakurisa** [Hakurisa/PAWS#7]
**Expected behavior**: Only the artist that created the album or song should be able to edit or delete them

**Current behavior**: Any user that has an Artist ID can edit any album or song by typing their IDs into the URL

**Comment by FirefoxV** [comment]
Musíš se zeptat na id umělce a v controlleru definovat podmínku, která vrátí třeba "isEditable" String pokud se id umělce shoduje s id umělce o které jsi řekneš z entity album

**Comment by FirefoxV** [comment]
poté dáš do html delete/editu ještě th:if="-vrácený string-"
